### ISSUE TITLE
OS X support？

### ISSUE THREAD

**Issue by guoxiao** [yahoo/mdbm#32]
I tried to build mdbm in OS X, but some linux related headers does not exist in OS X.
such as `syscall.h`, and some open file flags.
Will it support OS X in the future? Or if it's difficult to port it to OS X?

**Comment by timrc-git** [comment]
This issue also came up on the mailing-list. Re-posting my response here...

I think there will be two main issues to deal with. They are both
"fixable", but with some consequences.
  a) windowed-mode uses the linux-only remap_file_pages() call
  b) OSX doesn't seem to support "robust" pthreads mutexes

For remap_file_pages(), we could just add a flag to disable windowed-mode.
I've considered making a "lite" version of MDBM that just has the core features,
so that's a reasonable approach.
You could also partially emulate what remap_file_pages does with mmap, but it
will be much slower, and move the maps around in user memory.

For robust mutexes, there is already a HAVE_ROBUST_PTHREADS flag,
so you can disable attempts to use it. However, please note that if some
process fails to release a lock, then it will stall all later processes that try to use
that MDBM. At that point you would have to manually reset the lock, and then
you should run mdbm_check to make sure the DB is consistent.

Note that despite the suggestions here:
  http://stackoverflow.com/questions/24946886/is-there-pthread-mutex-robust-equivalent-in-mac-os-x
handlers for atexit() won't catch many kinds of unclean shutdown, and
having a daemon that kills arbitrary processes is likely to result in corruption or
other problems. Though if you wanted to do a lot of work, you could snoop the
pthreads structure from some daemon, and reset the lock if the owning process
was no longer running.

Cheers!
.timrc

**Comment by timrc-git** [comment]
Hi guoxiao, 

Evan provided patches for building on OSX, and we've been working on that on the 'osx' branch. Perhaps you'd like to help us test it?

Thanks!
.timrc

**Comment by timrc-git** [comment]
@eam, @areese 
Let's use this issue to wrap up the OSX branch.
Specifically, I'm looking for you two to tell me that it 
  a) compiles and runs on OSX, and 
  b) doesn't perform horribly 
before I merge it back into mainline.

Please let me know if you run into any issues. Thanks!

.timrc

**Comment by eam** [comment]
I'm making tests pass on OSX right now (mostly by ifdef'ing out, with notes where I can). Will test perf as well.

**Comment by eam** [comment]
Here are the timings for running the test suite on both linux and OSX: https://gist.github.com/eam/b0048f5e0c19413024c2

Total time to run 'make test' on OSX: 10m50s, linux: 8m20s

Note OSX runs fewer tests due to unimplemented features mentioned above. The full elapsed data should give a bit more color. I can run specific benchmarks as well if there's interest.

**Comment by eam** [comment]
I found an issue with growing the mdbm via mdbm_bench: I consistently hit this ENOMEM case: https://github.com/yahoo/mdbm/blob/master/src/lib/mdbm.c#L5091


Hacking around by just using a bigger mdbm:

```
$ src/tools/object/mdbm_bench -d 1280
<...>
nproc  fetch/s      msec  store/s      msec    del/s      msec  getpg/s      msec
    1  1591826   0.00000        0     0.000        0     0.000        0     0.000

```

**Comment by timrc-git** [comment]
It actually fails the same way for me on a 8GB linux box with the defaults,
but mdbm_bench is a bit persnickety. With -d 1280 it succeeds, and I see similar FPS.
Thanks!

**Comment by timrc-git** [comment]
@eam I created a HAVE_WINDOWED_MODE flag. I also centralized reset_getopt, and am hoping that it works for you (tests are re-enabled) now based on:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/getopt.3.html
Please let me know if the changes compile and tests pass for you now.

I'm still trying to figure out what to do with the write-protect tests (e.g. test_mdbm_openA16) in src/test/unit-test/test_open.cc. Might have to fork, run the test, and check that the child emitted SIGSEGV/SIGBUS.

Thanks!

**Comment by eam** [comment]
Excellent. I'm on BART and don't want to run a build on battery but I'll kick one off later today.

I did notice this issue: https://github.com/yahoo/mdbm/blob/osx/Makefile.base#L53

`LD_LIB_PATH` needs to be set similar to how it was previously using a conditional. It's a (perhaps confusingly named) make variable which contains both the name and value of the LD environment set for subprocesses. That is, the value of `LD_LIB_PATH` is something like `LD_LIBRARY_PATH=/path` (or DYLD on OSX). Check out how it's used here to interpolate its VAR=VAL contents in the shell command: https://github.com/yahoo/mdbm/blob/osx/Makefile.base#L204

I did the same thing originally and spent some time scratching my head until I noticed the difference between the "LIB" and "LIBRARY" in the names. Maybe `LD_LIB_PATH` should be renamed to something like `SHELL_ENVIRONMENT`?

**Comment by timrc-git** [comment]
Sorry, the "C" portion of my brain said "hey, double variable assigment, let's split that up".
Reverted, with a comment to reduce future confusion.

**Comment by eam** [comment]
Getopt was still broken, got out lldb and found the issue was argument ordering. GNU getopt is more lenient than the NetBSD version. Fix: https://github.com/yahoo/mdbm/pull/42

With that last PR the OSX branch looks good to me.

**Comment by eam** [comment]
I've created a homebrew tap for mdbm: https://github.com/eam/homebrew-mdbm

It would be great if this branch could get merged and a release tagged, at which point I can ask homebrew to merge the formula into their mainline so `brew install mdbm` will work on OSX out of the box. See: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#basic-instructions

With a tag I can create a tarball url to pull the particular version. Right now I'm pulling branch `osx` and homebrew won't prefer to merge a url which may change.

**Comment by guoxiao** [comment]
@eam you can submit it to `homebrew/homebrew-headonly` if a software has no stable version yet.

**Comment by eam** [comment]
Cool, I might do that. I'd love to have some releases tagged, though -- makes it easier to coordinate between packaging systems. I'm going to want rpms and debs as well.

**Comment by timrc-git** [comment]
@eam I merged the osx branch into mainline. Please let me know if you see any issues.
(Would have happened sooner, but I was out on vacation for a couple weeks and then playing catch-up).
Also, what's involved in tagging a release?
Thanks!

.timrc

**Comment by eam** [comment]
Perfect, thanks much -- and I hope you had a good vacation, heading out next week for my own :)

This should cover tagging a release, just a few clicks: https://help.github.com/articles/creating-releases/

**Comment by eam** [comment]
Bump - any chance we could get a tagged release? I'll add mdbm to a ton of packaging systems when we do.

**Comment by timrc-git** [comment]
@eam, this should have happened sooner, but I'm finally carving out some time to catch up on MDBM. 
Just tagged a release, after some minor bugfixes. 
Please let me know if you have any problems with it.

Thanks!
